version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    networks:
      - backend

  api-gateway:
    build: { context: ./api-gateway }
    container_name: api-gateway
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_JSON={
        "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
        }
    ports:
      - "8081:8081"
    depends_on: [eureka-server]
    networks: [backend]

  file-storing-service:
    build: { context: ./file-storing-service }
    container_name: file-storing-service
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_JSON={
        "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
        }
    ports:
      - "8083:8083"
    depends_on: [eureka-server]
    networks: [backend]

  file-analysis-service:
    build: { context: ./file-analysis-service }
    container_name: file-analysis-service
    environment:
      - SERVER_PORT=8084
      - SPRING_APPLICATION_JSON={
        "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
        }
    ports:
      - "8084:8084"
    depends_on: [eureka-server, file-storing-service]
    networks: [backend]

  my-api-gateway:
    build: { context: ./my-api-gateway }
    container_name: my-api-gateway
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_JSON={
        "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
        }
    ports:
      - "8082:8082"
    depends_on: [eureka-server, api-gateway, file-storing-service, file-analysis-service]
    networks: [backend]

networks:
  backend:
    driver: bridge
